// 图标映射工具 - 将图标名称映射到 FontAwesome 图标类名
export const iconMap: Record<string, string> = {
  Glasses: 'fa-glasses',
  Sword: 'fa-sword',
  Brain: 'fa-brain',
  Crown: 'fa-crown',
  Cat: 'fa-cat',
  Sparkles: 'fa-sparkles',
  User: 'fa-user',
  Dumbbell: 'fa-dumbbell',
  BookOpen: 'fa-book-open',
  Heart: 'fa-heart',
  Ghost: 'fa-ghost',
  Zap: 'fa-bolt',
  Flame: 'fa-fire',
  Shield: 'fa-shield',
  Target: 'fa-bullseye',
  RefreshCcw: 'fa-rotate-left',
  Eye: 'fa-eye',
  Dna: 'fa-dna',
  Music: 'fa-music',
  Camera: 'fa-camera',
  Scissors: 'fa-scissors',
  Hand: 'fa-hand',
  Wind: 'fa-wind',
  Anchor: 'fa-anchor',
  Feather: 'fa-feather',
  Smile: 'fa-face-smile',
  Skull: 'fa-skull',
  Mirror: 'fa-mirror',
  Gem: 'fa-gem',
  Droplets: 'fa-droplet',
  Mountain: 'fa-mountain',
  Footprints: 'fa-shoe-prints',
  FlaskConical: 'fa-flask',
  Users: 'fa-users',
  Disc: 'fa-compact-disc',
  HelpCircle: 'fa-circle-question',
  Cpu: 'fa-microchip',
  Wifi: 'fa-wifi',
  Star: 'fa-star',
  Settings: 'fa-gear',
  Flower: 'fa-flower',
  Terminal: 'fa-terminal',
  ChevronRight: 'fa-chevron-right',
  ChevronLeft: 'fa-chevron-left',
  Check: 'fa-check',
  Plus: 'fa-plus',
  Minus: 'fa-minus',
  TrendingUp: 'fa-arrow-trend-up',
  Activity: 'fa-chart-line',
};

export function getIconClass(iconName: string): string {
  return iconMap[iconName] || 'fa-circle';
}
